### ISSUE TITLE
rubocop導入

### ISSUE THREAD

**Issue by yuki-tachi0219** [quest-academia/qa-rails-ec-training-violet#26]

**Comment by yuki-tachi0219** [comment]
Gemfileに、
- rubocop
- rubocop-rails
- rubocop-rspec

の3つを入れること。

onkcopリポジトリの、config下のファイルをコピーして、
config/rubocop/
の下にペーストすること。対象ファイルは、performance.yml以外全部。

設定ファイル `.rubocop.yml` を作成し、

```
require:
  - rubocop-rails
  - rubocop-rspec

inherit_from:
  - "config/rubocop/rails.yml"
  - "config/rubocop/rubocop.yml"
  - "config/rubocop/rspec.yml"

AllCops:
  TargetRubyVersion: *.*.*
  TargetRailsVersion: *.*.*.*
```
